[package]
name = "stream-start-screen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.54.0"
glow = "0.13.0"
freetype-rs = "0.34.0"
thiserror = "1.0.50"
chrono = "0.4.31"
png = "0.17.10"
